create a numpy ndarray object 

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


dimensions in aaray

In [3]:
#0D array
import numpy as np
arr = np.array(42)
print(arr)

42


In [4]:
#1D array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
#2D array
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [6]:
#3D array
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


check number of dimensions

In [8]:
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3,4,5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


higher dimensions arrays

In [13]:
import numpy as np
arr = np.array([1,2,3,4],ndmin = 5)
print(arr)
print("number of dimensions : " arr ndmin)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1829515270.py, line 4)

access array elements 

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print (arr[0])
print (arr[1])
rint(arr[2]+arr[3])

1
2
7


access 2-D array

In [2]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row: ',arr[0,1])
print('5th element on 2nd row: ',arr[1,4])

2nd element on 1st row:  2
5th element on 2nd row:  10


access 3d arrayS

In [3]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


negative indexing 

In [6]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('last element from 2nd dimensions: ',arr[1,-1])

last element from 2nd dimensions:  10


slicing arrays

In [8]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


slicing 2d arrays

In [10]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0:2,2])
print(arr[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


numpy datatypes 